# Inserts a blank line between shell prompts
add_newline = true

format = "$time$all"

[time]
disabled = false
time_format = "%H:%M:%S"
format = "[$time]($style) "
style = "dimmed white"

[git_branch]
symbol = "ðŸŒ¿ "
